name: Generar Metricas de PageSpeed
on:
  # Ejecutar automáticamente todos los días
  schedule: [{cron: "0 0 * * *"}]
  # Ejecutar cuando se haga un cambio en el código
  push: {branches: ["master", "main"]}
  # Permitir ejecutarlo manualmente desde GitHub
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Generar PageSpeed
        uses: lowlighter/metrics@latest
        with:
          # Guardar la imagen generada en la carpeta assets
          filename: assets/pagespeed.svg
          # Token automático de GitHub (no necesitas configurar nada)
          token: ${{ secrets.GITHUB_TOKEN }}
          # Desactivar estadísticas base para mostrar SOLO PageSpeed
          base: ""
          # Configuración del plugin
          plugin_pagespeed: yes
          plugin_pagespeed_detailed: yes
          extras_css: |
            h2.field, h2.field + .field, .audits { display: none !important; }
            .gauge text { font-size: 55px !important; font-weight: 900 !important; }
          plugin_pagespeed_url: https://astro-web14.netlify.app/
          plugin_pagespeed_token: ${{ secrets.PAGESPEED_TOKEN }}
